### ISSUE TITLE
navigate fails with options

### ISSUE THREAD

**Issue by zwz** [WebReflection/hyperhtml-app#1]
See https://codepen.io/anon/pen/MEaPdJ?editors=0010
Go to "setting" page, there are one button and one link, and they both should navigate to "home" page when clicked. But the former fails.

**Comment by WebReflection** [comment]
Currently, the only functionality provided by `options` optional argument is to have either a `replace` or `replaceState` truthy value, nothing else.

What `options` does, when one of those two properties are set, is simply to replace the current history state without triggering an event, preventing the history object to be polluted with possible useless states.

> If there is a second options parameter and it has a replace or replaceState truthy property, it will not trigger a navigation event but it will replace the latest history with the current URL (shortcut for history.replaceState(...)).

What you are doing there, is passing a state, but i have no idea what you'd expect that to do so this is technically not a bug, it was never meant to accept objects 'till now.

On the other hand, using just navigate will re-render without any issue the link and if you don't create a new Settings each time, as shown in [this Code Pen fork](https://codepen.io/WebReflection/pen/NaGZrN?editors=0010), your state will be kept with the right value.

**Comment by zwz** [comment]
Well, at first I thought `options` was a good way to share data (e.g state) between two components.

**Comment by WebReflection** [comment]
how would you retrieve that data back ? You can always use a special `data` attribute to pass data along, dispatch events to bubble data via CustomEvents, etcetera

**Comment by zwz** [comment]
I just misunderstood the usage of `options` :)
Thank you for your answer.

**Comment by WebReflection** [comment]
the polyfill works already but for properly transpiled classes you need IE11 or greater.
