### ISSUE TITLE
Docs: add practical usage example

### ISSUE THREAD

**Issue by jiayihu** [WebReflection/hyperhtml-app#3]
It would be nice to add more documentation examples about its usage. I've had a quick look at [viper-news](https://github.com/WebReflection/viper-news) to get started about its usage, but I was lucky to find another issue mentioning the Hacker News app as router example.

Along with HyperHTMLElement, I use it as following:

```typescript
import HyperHTMLElement from 'hyperhtml-element';
import hyperApp, { Ctx } from 'hyperhtml-app';

const { bind } = HyperHTMLElement;

export class App extends HyperHTMLElement {
  private routerOutletEl: HTMLElement = document.createElement('div');
  private router = new hyperApp();
  private renderRoute = bind(this.routerOutletEl);

  constructor() {
    super();

    this.attachShadow({ mode: 'open' });
  }

  private handleUserRoute = (ctx: Ctx) => {
    const userName = ctx.params.name;

    this.renderRoute`<my-user-page name=${userName} />`;
    this.render();
  };

  private handleHomeRoute = () => {
    this.renderRoute`<h1>Home</h1>`;
    this.render();
  };

  private configureRoutes() {
    this.router.get('/user/:name', this.handleUserRoute);
    this.router.get('/', this.handleHomeRoute);
  }

  private getCurrentRoute(): string {
    return window.location.pathname.replace('index.html', '');
  }

  created() {
    this.configureRoutes();

    // Trigger route handler for the current path
    this.router.navigate(this.getCurrentRoute());
  }

  handleRouteChange = (event: RouteChangeEvent): void => {
    const route: string = event.detail.route;
    this.router.navigate(route);
  };

  render() {
    const activeRoute = this.getCurrentRoute();

    return this.html`
      <my-navbar route=${activeRoute} onrouteChange=${this.handleRouteChange}></my-navbar>
      <div class="container">
        ${this.routerOutletEl}
      </div>
    `;
  }
}

App.define('my-app');
```

Is it a correct way to use the library? I'd like to move the router configuration to be more declarative in `render` or more static out of the component, but without a state management library, `App` is responsible for some logic between the routes. You can find the complete source code here: [jiayihu/ygo](https://github.com/jiayihu/ygo/blob/master/src/components/App/App.ts).

I could make a PR with a similar example but with pure hyperHTML if it's okay.

**Comment by WebReflection** [comment]
> Is it a correct way to use the library?

it's an awesome way! I'd probably simplify the render though, also remember you don't need to close tags that have no content, _hyperHTML_ handles that for you.

```js
  render() {
    this.html`
      <my-navbar
        route=${this.getCurrentRoute()}
        onrouteChange=${this.handleRouteChange}
      />
      <div class="container">
        ${this.routerOutletEl}
      </div>
    `;
  }
```

> I could make a PR with a similar example but with pure hyperHTML if it's okay.

If with a linked CodePen (or other similar live tools) too, it'd be more than welcome, thanks!

**Comment by jiayihu** [comment]
> it's an awesome way!

Oh, that's a relief!

> also remember you don't need to close tags that have no content, hyperHTML handles that for you

Yup I know and that's a very nice touch indeed. I don't remember if it was `<my-navbar>`, but I had a strange case where the resulting HTML would wrap the next sibling if I didn't close the tag. In this case it would have resulted in `<my-navbar><div class="container">...</div></my-navbar>`.

But I think it's hardly a bug of hyperHTML. One issue with HTML template literals is that I don't have built-in validation for the syntax, maybe I just missed a closing tag somewhere in the app. It would be nice having hyperHTML trying to validate the syntax in the development stage, like Angular does, but I suppose it's a hell.

Anyway, I'll update the issue with a PR and working Codepen ASAP 💃

**Comment by WebReflection** [comment]
> I had a strange case where the resulting HTML would wrap the next sibling if I didn't close the tag.

that's what DOM would do, but hyperHTML *shouldn't* ™️

> One issue with HTML template literals is that I don't have built-in validation for the syntax

have you tried [literally-html](https://github.com/WebReflection/vscode-literally-html#literally-html) ?

it doesn't validate but at least it highlights html in a JSXish style.

**Comment by jiayihu** [comment]
> have you tried literally-html ?

Yup first extension I've installed. I'll maybe take another chance to discover the reason

**Comment by jiayihu** [comment]
Okay, unfortunately, I was not able to make it work on Codepen because it doesn't support routing and examples have a strange path. I've made instead an example using Stackblitz: [https://stackblitz.com/edit/hyperhtml-app?file=index.js](https://stackblitz.com/edit/hyperhtml-app) with the following code:

```js
/**
 * Utilities
 */

function getCurrentRoute() {
  return window.location.pathname.replace('index.html', '');
}

/**
 * Main app
 */

const routerOutletEl = document.createElement('div');
const router = new hyperHTML.app();
const renderRoute = hyperHTML.bind(routerOutletEl);

router.get('/user/:name', ctx => {
  const userName = ctx.params.name
  
  renderRoute`
    <h1>Hello ${userName}</h1>
    <button onclick=${() => router.navigate('/')}>
      Go back
    </button>
  `
  render()
});
router.get('/', () => {
  renderRoute`
    <h1>Hello world</h1>
    <button onclick=${() => router.navigate('/user/Julia')}>
      See Julia
    </button>
    <button onclick=${() => router.navigate('/user/Andrea')}>
      See Andrea
    </button>
  `
  render()
});

const html = hyperHTML.bind(document.getElementById('root'))
function render() {
  return html`
    <div>
      ${routerOutletEl}
    </div>
  `;
}

// Trigger route handler for the initial route
router.navigate(getCurrentRoute());
```

Let me know what's your opinion on it, if it's fine I'm going to open a PR.

**Comment by WebReflection** [comment]
I thin as demo is great, thanks!
