### ISSUE TITLE
app.use middleware next() doesn't work

### ISSUE THREAD

**Issue by jaschaio** [WebReflection/hyperhtml-app#6]
When I invoke `next()` from within the `app.use` callback nothing happens.

Simple Example:

```javascript
const app = hyperApp();

app.use( [ '*' ], ( ctx, next ) => {
    console.log( ctx.params );
    next();
} );

app.param( 'page', ( ctx, next, name ) => {
    console.log( name );
    next();
} );

app.get( '/:page', ( ctx, next ) => {
    console.log( `render ${ ctx.params.page }` );
} );

app.navigate( '/about' );
```

This should log the Following:

```
{ 0: '/about' }
about
render about
```

But it only logs the `ctx.params`, the rest of the routes are never invoked even if `next()` has been called.

If I remove the `app.use( ... )` part it works.

What I am trying to do is applying a middleware to all routes like in express. What actually wonders me that I need to give a path as the first parameter to `app.use` as within express I just pass in the middleware directly.

**Comment by WebReflection** [comment]
please let me know if `v1.0.1` fixed it, thanks
